# Generated by Django 5.2.17 on 2026-08-25 04:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_PUBLICATION", "New publication"),
                            ("ACK_REQUIRED", "Acknowledgement required"),
                            ("COMMENT_REPLY", "Comment reply"),
                            ("COMMENT_MENTION", "Comment mention"),
                            ("NEW_MESSAGE", "New message"),
                            ("MESSAGE_MENTION", "Message mention"),
                            ("CHAT_ADDED", "Added to chat"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_type", models.CharField(max_length=32)),
                ("source_id", models.UUIDField()),
                ("publication_id", models.UUIDField(blank=True, null=True)),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("dedupe_key", models.CharField(max_length=160)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("event_version", models.PositiveIntegerField(default=1)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_event_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_event_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("PUSH", "Push"), ("EMAIL", "Email")], max_length=8),
                ),
                ("event_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationFanoutEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_key", models.CharField(max_length=200, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("NEW_PUBLICATION", "New publication"),
                            ("ACK_REQUIRED", "Acknowledgement required"),
                            ("COMMENT_REPLY", "Comment reply"),
                            ("COMMENT_MENTION", "Comment mention"),
                            ("NEW_MESSAGE", "New message"),
                            ("MESSAGE_MENTION", "Message mention"),
                            ("CHAT_ADDED", "Added to chat"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("payload", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["processed_at", "available_at"], name="notif_fanout_pending_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_PUBLICATION", "New publication"),
                            ("ACK_REQUIRED", "Acknowledgement required"),
                            ("COMMENT_REPLY", "Comment reply"),
                            ("COMMENT_MENTION", "Comment mention"),
                            ("NEW_MESSAGE", "New message"),
                            ("MESSAGE_MENTION", "Message mention"),
                            ("CHAT_ADDED", "Added to chat"),
                        ],
                        max_length=32,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read_at", "-last_event_at"], name="notification_inbox_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("read_at__isnull", True)),
                fields=("recipient", "dedupe_key"),
                name="notification_unread_group_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status", "available_at"], name="notification_delivery_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel", "event_version"),
                name="notification_delivery_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "notification_type"), name="notification_preference_unique"
            ),
        ),
    ]
