FROM postgres:18.6-alpine

COPY infra/postgres/search/hunspell-kk/kk_KZ.aff /usr/local/share/postgresql/tsearch_data/tandem_kk.affix
COPY infra/postgres/search/hunspell-kk/kk_KZ.dic /usr/local/share/postgresql/tsearch_data/tandem_kk.dict
