# Generated by Django 5.2.17 on 2026-08-25 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0002_messageattachment_messagereaction_messagerevision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="discussion_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversationmembership",
            name="notification_mode",
            field=models.CharField(
                choices=[("ALL", "All"), ("MENTIONS", "Mentions"), ("NONE", "None")],
                default="ALL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CHAT", "Chat message"),
                    ("CHANNEL_POST", "Channel post"),
                    ("DISCUSSION", "Discussion"),
                ],
                default="CHAT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="mention_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[("DIRECT", "Direct"), ("GROUP", "Group"), ("CHANNEL", "Channel")],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="conversationmembership",
            name="role",
            field=models.CharField(
                choices=[("MEMBER", "Member"), ("WRITER", "Writer"), ("ADMIN", "Admin")],
                default="MEMBER",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="MessageMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="messenger.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user"), name="messenger_message_mention_unique"
                    )
                ],
            },
        ),
    ]
