# Generated by Django 5.2.17 on 2026-08-25 04:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_language_configurations"),
        ("messenger", "0003_conversation_discussion_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="messenger_message_fts_idx",
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("body", config="russian"),
                name="msg_search_ru_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("body", config="tandem_kazakh"),
                name="msg_search_kk_idx",
            ),
        ),
    ]
