# Generated by Django 5.2.17 on 2026-08-25 08:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0004_remove_message_messenger_message_fts_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DISMISSED", "Dismissed"),
                            ("MESSAGE_DELETED", "Message deleted"),
                            ("AUTHOR_RESTRICTED", "Author restricted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("moderator_note", models.CharField(blank=True, max_length=500)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="messenger.message",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderated_messenger_message_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messenger_message_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["state", "-created_at"], name="msg_report_queue_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "reporter"), name="messenger_message_reporter_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessengerRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_messenger_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messenger_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at", "expires_at"],
                        name="messenger_restrict_active_idx",
                    )
                ],
            },
        ),
    ]
