# Generated by Django 5.2.17 on 2026-08-23 09:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.publications.rich_text


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["sort_order", "name", "id"]},
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("summary", models.TextField(max_length=1000)),
                (
                    "body",
                    models.JSONField(
                        default=apps.publications.rich_text.empty_rich_text_document,
                        validators=[apps.publications.rich_text.validate_rich_text_document],
                    ),
                ),
                ("body_text", models.TextField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="publications.category",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="AudienceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ALL", "All employees"),
                            ("ORG_UNIT", "Organization unit"),
                            ("EMPLOYEE", "Employee"),
                            ("MODULE_ROLE", "Module role"),
                        ],
                        max_length=32,
                    ),
                ),
                ("module_role", models.CharField(blank=True, max_length=64)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_portal_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_audience_rules",
                        to=settings.AUTH_USER_MODEL,
                        to_field="portal_id",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="org_unit_external_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_audience_rules",
                        to="organization.orgunit",
                        to_field="external_id",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_rules",
                        to="publications.publication",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="PublicationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_viewed_at", models.DateTimeField()),
                ("last_viewed_at", models.DateTimeField()),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="publications.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-last_viewed_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["status", "-published_at", "-id"],
                name="publications_feed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "DRAFT"), _negated=True),
                    ("published_at__isnull", True),
                    _connector="OR",
                ),
                name="publication_draft_has_no_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "PUBLISHED"), _negated=True),
                    ("published_at__isnull", False),
                    _connector="OR",
                ),
                name="publication_published_has_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("employee__isnull", True),
                        ("kind", "ALL"),
                        ("module_role", ""),
                        ("org_unit__isnull", True),
                    ),
                    models.Q(
                        ("employee__isnull", True),
                        ("kind", "ORG_UNIT"),
                        ("module_role", ""),
                        ("org_unit__isnull", False),
                    ),
                    models.Q(
                        ("employee__isnull", False),
                        ("kind", "EMPLOYEE"),
                        ("module_role", ""),
                        ("org_unit__isnull", True),
                    ),
                    models.Q(
                        ("employee__isnull", True),
                        ("kind", "MODULE_ROLE"),
                        ("org_unit__isnull", True),
                        models.Q(("module_role", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="audience_rule_target_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "ALL")),
                fields=("publication", "kind"),
                name="audience_rule_all_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "ORG_UNIT")),
                fields=("publication", "org_unit"),
                name="audience_rule_org_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "EMPLOYEE")),
                fields=("publication", "employee"),
                name="audience_rule_employee_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "MODULE_ROLE")),
                fields=("publication", "module_role"),
                name="audience_rule_role_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="publicationview",
            index=models.Index(
                fields=["user", "-last_viewed_at"],
                name="publication_view_user_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationview",
            constraint=models.UniqueConstraint(
                fields=("publication", "user"),
                name="publication_view_user_unique",
            ),
        ),
    ]
