# Generated by Django 5.2.17 on 2026-08-23 09:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SEARCH_INDEX = django.contrib.postgres.indexes.GinIndex(
    django.contrib.postgres.search.SearchVector("title", config="simple", weight="A")
    + django.contrib.postgres.search.SearchVector("summary", config="simple", weight="B")
    + django.contrib.postgres.search.SearchVector("body_text", config="simple", weight="C"),
    name="publications_search_idx",
)


def create_search_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.add_index(apps.get_model("publications", "Publication"), SEARCH_INDEX)


def remove_search_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.remove_index(apps.get_model("publications", "Publication"), SEARCH_INDEX)


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("publication.created", "Publication created"),
                            ("publication.updated", "Publication updated"),
                            ("publication.published", "Publication published"),
                        ],
                        max_length=64,
                    ),
                ),
                ("previous_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_search_index, remove_search_index),
            ],
            state_operations=[
                migrations.AddIndex(model_name="publication", index=SEARCH_INDEX),
            ],
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="publications.publication",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["publication", "created_at"], name="publication_audit_idx"),
        ),
    ]
