# Generated by Django 5.2.17 on 2026-08-23 14:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.publications.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
        ("publications", "0002_auditevent_publication_publications_search_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(editable=False, max_length=255, unique=True)),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=apps.publications.models.media_storage_path
                    ),
                ),
                ("mime_type", models.CharField(max_length=128)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video"), ("DOCUMENT", "Document")],
                        max_length=16,
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("READY", "Ready"), ("REJECTED", "Rejected")],
                        default="READY",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MediaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("COVER", "Cover"),
                            ("BODY", "Body"),
                            ("ATTACHMENT", "Attachment"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PublicationPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slot", models.PositiveSmallIntegerField(unique=True)),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["slot"],
            },
        ),
        migrations.CreateModel(
            name="PublicationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=64)),
                ("snapshot", models.JSONField()),
                ("changed_fields", models.JSONField(default=list)),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="audiencerule",
            name="audience_rule_target_shape",
        ),
        migrations.RemoveConstraint(
            model_name="publication",
            name="publication_draft_has_no_date",
        ),
        migrations.AddField(
            model_name="audiencerule",
            name="include_descendants",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="audiencerule",
            name="position_group_external_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="audiencerule",
            name="position_group_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publication",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="edit_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="publication",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="last_autosaved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="unpublished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiencerule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ALL", "All employees"),
                    ("ORG_UNIT", "Organization unit"),
                    ("EMPLOYEE", "Employee"),
                    ("MODULE_ROLE", "Module role"),
                    ("POSITION_GROUP", "Position group"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("publication.created", "Publication created"),
                    ("publication.updated", "Publication updated"),
                    ("publication.published", "Publication published"),
                    ("publication.transitioned", "Publication transitioned"),
                    ("publication.duplicated", "Publication duplicated"),
                    ("publication.pinned", "Publication pinned"),
                    ("publication.unpinned", "Publication unpinned"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_REVIEW", "In review"),
                    ("SCHEDULED", "Scheduled"),
                    ("PUBLISHED", "Published"),
                    ("UNPUBLISHED", "Unpublished"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("employee__isnull", True),
                        ("include_descendants", False),
                        ("kind", "ALL"),
                        ("module_role", ""),
                        ("org_unit__isnull", True),
                        ("position_group_external_id", ""),
                        ("position_group_name", ""),
                    ),
                    models.Q(
                        ("employee__isnull", True),
                        ("kind", "ORG_UNIT"),
                        ("module_role", ""),
                        ("org_unit__isnull", False),
                        ("position_group_external_id", ""),
                        ("position_group_name", ""),
                    ),
                    models.Q(
                        ("employee__isnull", False),
                        ("include_descendants", False),
                        ("kind", "EMPLOYEE"),
                        ("module_role", ""),
                        ("org_unit__isnull", True),
                        ("position_group_external_id", ""),
                        ("position_group_name", ""),
                    ),
                    models.Q(
                        ("employee__isnull", True),
                        ("include_descendants", False),
                        ("kind", "MODULE_ROLE"),
                        ("org_unit__isnull", True),
                        ("position_group_external_id", ""),
                        ("position_group_name", ""),
                        models.Q(("module_role", ""), _negated=True),
                    ),
                    models.Q(
                        ("employee__isnull", True),
                        ("include_descendants", False),
                        ("kind", "POSITION_GROUP"),
                        ("module_role", ""),
                        ("org_unit__isnull", True),
                        models.Q(("position_group_external_id", ""), _negated=True),
                        models.Q(("position_group_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="audience_rule_target_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencerule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "POSITION_GROUP")),
                fields=("publication", "position_group_external_id"),
                name="audience_rule_position_group_unique",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_media_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_publications",
                to="publications.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="mediausage",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usages",
                to="publications.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="mediausage",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_usages",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationpin",
            name="pinned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication_pins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicationpin",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pin",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationversion",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicationversion",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="publications.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "SCHEDULED"), _negated=True),
                    ("scheduled_for__isnull", False),
                    _connector="OR",
                ),
                name="publication_scheduled_has_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ARCHIVED"), _negated=True),
                    ("archived_at__isnull", False),
                    _connector="OR",
                ),
                name="publication_archived_has_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediausage",
            constraint=models.UniqueConstraint(
                fields=("asset", "publication", "purpose"), name="media_usage_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationpin",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot__gte", 1), ("slot__lte", 5)),
                name="publication_pin_slot_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationversion",
            constraint=models.UniqueConstraint(
                fields=("publication", "version_number"), name="publication_version_number_unique"
            ),
        ),
    ]
