# Generated by Django 5.2.17 on 2026-08-23 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_mediaasset_mediausage_publicationpin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["DRAFT", "IN_REVIEW", "SCHEDULED"]), _negated=True),
                    ("published_at__isnull", True),
                    _connector="OR",
                ),
                name="publication_prepublication_has_no_date",
            ),
        ),
    ]
