# Generated by Django 5.2.17 on 2026-08-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_publication_targets(apps, _schema_editor):
    AuditEvent = apps.get_model("publications", "AuditEvent")
    for event in AuditEvent.objects.filter(target_id="").iterator():
        event.target_id = str(event.publication_id)
        event.save(update_fields=["target_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_publication_publication_prepublication_has_no_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="new_state",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="target_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("publication", "Publication"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("media", "Media"),
                ],
                default="publication",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("publication.created", "Publication created"),
                    ("publication.updated", "Publication updated"),
                    ("publication.published", "Publication published"),
                    ("publication.transitioned", "Publication transitioned"),
                    (
                        "publication.submitted_for_review",
                        "Publication submitted for review",
                    ),
                    ("publication.returned_to_draft", "Publication returned to draft"),
                    ("publication.scheduled", "Publication scheduled"),
                    ("publication.schedule_cancelled", "Publication schedule cancelled"),
                    ("publication.unpublished", "Publication unpublished"),
                    ("publication.archived", "Publication archived"),
                    ("publication.duplicated", "Publication duplicated"),
                    ("publication.pinned", "Publication pinned"),
                    ("publication.unpinned", "Publication unpinned"),
                    ("taxonomy.category.created", "Category created"),
                    ("taxonomy.category.updated", "Category updated"),
                    ("taxonomy.tag.created", "Tag created"),
                    ("taxonomy.tag.updated", "Tag updated"),
                    ("media.uploaded", "Media uploaded"),
                    ("media.deleted", "Media deleted"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="publications.publication",
            ),
        ),
        migrations.RunPython(backfill_publication_targets, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["target_type", "target_id", "created_at"],
                name="module_audit_target_idx",
            ),
        ),
    ]
