# Generated by Django 5.2.17 on 2026-08-24 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0005_auditevent_new_state_auditevent_target_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="comment_attachments_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="acknowledgement_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="reactions_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("publication.created", "Publication created"),
                    ("publication.updated", "Publication updated"),
                    ("publication.published", "Publication published"),
                    ("publication.transitioned", "Publication transitioned"),
                    ("publication.submitted_for_review", "Publication submitted for review"),
                    ("publication.returned_to_draft", "Publication returned to draft"),
                    ("publication.scheduled", "Publication scheduled"),
                    ("publication.schedule_cancelled", "Publication schedule cancelled"),
                    ("publication.unpublished", "Publication unpublished"),
                    ("publication.archived", "Publication archived"),
                    ("publication.duplicated", "Publication duplicated"),
                    ("publication.pinned", "Publication pinned"),
                    ("publication.unpinned", "Publication unpinned"),
                    ("taxonomy.category.created", "Category created"),
                    ("taxonomy.category.updated", "Category updated"),
                    ("taxonomy.tag.created", "Tag created"),
                    ("taxonomy.tag.updated", "Tag updated"),
                    ("media.uploaded", "Media uploaded"),
                    ("media.deleted", "Media deleted"),
                    ("comment.hidden", "Comment hidden"),
                    ("comment.restored", "Comment restored"),
                    ("comment.removed", "Comment removed"),
                    ("report.resolved", "Report resolved"),
                    ("user.commenting_restricted", "User commenting restricted"),
                    ("restriction.revoked", "Restriction revoked"),
                    ("engagement.settings_updated", "Engagement settings updated"),
                    ("publication.discussion_closed", "Discussion closed"),
                    ("publication.discussion_opened", "Discussion opened"),
                    ("stop_word.created", "Stop word created"),
                    ("stop_word.disabled", "Stop word disabled"),
                    ("publication.acknowledged", "Publication acknowledged"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("publication", "Publication"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("media", "Media"),
                    ("comment", "Comment"),
                    ("report", "Report"),
                    ("user", "User"),
                    ("settings", "Settings"),
                    ("acknowledgement", "Acknowledgement"),
                ],
                default="publication",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PublicationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("portal_id", models.CharField(max_length=128)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("org_unit_external_id", models.CharField(blank=True, max_length=128)),
                ("org_unit_name", models.CharField(blank=True, max_length=255)),
                ("is_current", models.BooleanField(default=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipient_snapshots",
                        to="publications.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "portal_id"],
            },
        ),
        migrations.CreateModel(
            name="Acknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledgements",
                        to="publications.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledgements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledgement",
                        to="publications.publicationrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["acknowledged_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="publicationrecipient",
            index=models.Index(
                fields=["publication", "is_current"], name="pub_recipient_current_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationrecipient",
            index=models.Index(
                fields=["publication", "portal_id"], name="pub_recipient_portal_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrecipient",
            constraint=models.UniqueConstraint(
                fields=("publication", "portal_id"), name="pub_recipient_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="acknowledgement",
            constraint=models.UniqueConstraint(
                fields=("publication", "user"), name="publication_ack_user_unique"
            ),
        ),
    ]
