# Generated by Django 5.2.17 on 2026-08-25 04:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_language_configurations"),
        ("publications", "0010_mediaasset_is_messenger_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="publication",
            name="publications_search_idx",
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("original_name", config="russian"),
                name="media_search_ru_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "original_name", config="tandem_kazakh"
                ),
                name="media_search_kk_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "title", config="russian", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "summary", config="russian", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig("russian"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "body_text", config="russian", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("russian"),
                ),
                name="pub_search_ru_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "title", config="tandem_kazakh", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "summary", config="tandem_kazakh", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig("tandem_kazakh"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "body_text", config="tandem_kazakh", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("tandem_kazakh"),
                ),
                name="pub_search_kk_idx",
            ),
        ),
    ]
