# Generated by Django 5.2.17 on 2026-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0011_remove_publication_publications_search_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("publication.created", "Publication created"),
                    ("publication.updated", "Publication updated"),
                    ("publication.published", "Publication published"),
                    ("publication.transitioned", "Publication transitioned"),
                    ("publication.submitted_for_review", "Publication submitted for review"),
                    ("publication.returned_to_draft", "Publication returned to draft"),
                    ("publication.scheduled", "Publication scheduled"),
                    ("publication.schedule_cancelled", "Publication schedule cancelled"),
                    ("publication.unpublished", "Publication unpublished"),
                    ("publication.archived", "Publication archived"),
                    ("publication.duplicated", "Publication duplicated"),
                    ("publication.pinned", "Publication pinned"),
                    ("publication.unpinned", "Publication unpinned"),
                    ("taxonomy.category.created", "Category created"),
                    ("taxonomy.category.updated", "Category updated"),
                    ("taxonomy.tag.created", "Tag created"),
                    ("taxonomy.tag.updated", "Tag updated"),
                    ("media.uploaded", "Media uploaded"),
                    ("media.deleted", "Media deleted"),
                    ("comment.hidden", "Comment hidden"),
                    ("comment.restored", "Comment restored"),
                    ("comment.removed", "Comment removed"),
                    ("report.resolved", "Report resolved"),
                    ("user.commenting_restricted", "User commenting restricted"),
                    ("restriction.revoked", "Restriction revoked"),
                    ("engagement.settings_updated", "Engagement settings updated"),
                    ("publication.discussion_closed", "Discussion closed"),
                    ("publication.discussion_opened", "Discussion opened"),
                    ("stop_word.created", "Stop word created"),
                    ("stop_word.disabled", "Stop word disabled"),
                    ("publication.acknowledged", "Publication acknowledged"),
                    ("messenger.member.added", "Messenger member added"),
                    ("messenger.member.removed", "Messenger member removed"),
                    ("messenger.member.role_changed", "Messenger member role changed"),
                    ("messenger.message.edited", "Messenger message edited"),
                    ("messenger.message.sent", "Messenger message sent"),
                    ("messenger.message.deleted", "Messenger message deleted"),
                    ("messenger.message.forwarded", "Messenger message forwarded"),
                    ("messenger.reaction.changed", "Messenger reaction changed"),
                    ("messenger.message.pinned", "Messenger message pinned"),
                    ("messenger.message.unpinned", "Messenger message unpinned"),
                    ("messenger.message.reported", "Messenger message reported"),
                    ("messenger.report.resolved", "Messenger report resolved"),
                    ("messenger.user.restricted", "Messenger user restricted"),
                ],
                max_length=64,
            ),
        ),
    ]
