# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0012_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="temporary_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
