# Generated by Django 5.2.17 on 2026-08-24 05:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.discussions.models


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0001_initial"),
        ("publications", "0006_category_comment_attachments_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CommentMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommentRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EngagementSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment_edit_window_minutes", models.PositiveIntegerField(default=60)),
                ("comment_delete_window_minutes", models.PositiveIntegerField(default=60)),
                (
                    "enabled_reaction_types",
                    models.JSONField(default=apps.discussions.models.default_reaction_types),
                ),
                ("max_comment_attachments", models.PositiveSmallIntegerField(default=5)),
                ("max_comment_attachment_bytes", models.PositiveIntegerField(default=26214400)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModerationFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("matched_word", models.CharField(max_length=100)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("COMMENT_REPLY", "Comment reply"),
                            ("COMMENT_MENTION", "Comment mention"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StopWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=100, unique=True)),
                ("normalized_value", models.CharField(editable=False, max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["value", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RemoveConstraint(
            model_name="comment",
            name="comment_deleted_shape",
        ),
        migrations.RemoveConstraint(
            model_name="reaction",
            name="reaction_publication_user_type_unique",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="comment_pub_page_idx",
        ),
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_replies",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="thread_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="thread_replies",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DELETED", "Deleted by author"),
                    ("HIDDEN", "Hidden for moderation"),
                    ("REMOVED", "Removed by moderator"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="publications.publication",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("LIKE", "Like"),
                    ("CELEBRATE", "Celebrate"),
                    ("SUPPORT", "Support"),
                    ("INSIGHTFUL", "Insightful"),
                    ("THANKS", "Thanks"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["publication", "thread_root", "-created_at", "-id"],
                name="comment_thread_page_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["reply_to"], name="comment_reply_to_idx"),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["comment", "reaction_type"], name="reaction_comment_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reply_to__isnull", True), ("thread_root__isnull", True)),
                    models.Q(("reply_to__isnull", False), ("thread_root__isnull", False)),
                    _connector="OR",
                ),
                name="comment_thread_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deleted_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("deleted_at__isnull", True), ("status", "HIDDEN")),
                    models.Q(("body", ""), ("deleted_at__isnull", False), ("status", "DELETED")),
                    models.Q(("deleted_at__isnull", False), ("status", "REMOVED")),
                    _connector="OR",
                ),
                name="comment_status_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("comment__isnull", True), ("publication__isnull", False)),
                    models.Q(("comment__isnull", False), ("publication__isnull", True)),
                    _connector="OR",
                ),
                name="reaction_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("publication__isnull", False)),
                fields=("publication", "user"),
                name="reaction_publication_user_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("comment", "user"),
                name="reaction_comment_user_unique",
            ),
        ),
        migrations.AddField(
            model_name="commentattachment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_attachments",
                to="publications.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="commentattachment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentmention",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentmention",
            name="mentioned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_mentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentreport",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentreport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_comment_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentrestriction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_restrictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentrestriction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_restrictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moderationflag",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flags",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="commentattachment",
            constraint=models.UniqueConstraint(
                fields=("comment", "asset"), name="comment_attachment_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentmention",
            constraint=models.UniqueConstraint(
                fields=("comment", "mentioned_user"), name="comment_mention_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="commentreport",
            index=models.Index(fields=["status", "-created_at"], name="comment_report_queue_idx"),
        ),
        migrations.AddConstraint(
            model_name="commentreport",
            constraint=models.UniqueConstraint(
                fields=("comment", "reporter"), name="comment_reporter_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="commentrestriction",
            index=models.Index(
                fields=["user", "revoked_at", "expires_at"], name="restriction_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="moderationflag",
            constraint=models.UniqueConstraint(
                fields=("comment", "matched_word"), name="comment_flag_word_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "comment"), name="notification_recipient_comment_unique"
            ),
        ),
    ]
