# Generated by Django 5.2.17 on 2026-08-25 04:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_language_configurations"),
        ("discussions", "0003_remove_legacy_notification"),
        ("publications", "0011_remove_publication_publications_search_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("body", config="russian"),
                name="comment_search_ru_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("body", config="tandem_kazakh"),
                name="comment_search_kk_idx",
            ),
        ),
    ]
