# Generated by Django 5.2.17 on 2026-08-25 08:35

from django.db import migrations, models

import apps.discussions.models


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0004_comment_comment_search_ru_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementsettings",
            name="allowed_media_extensions",
            field=models.JSONField(default=apps.discussions.models.default_media_extensions),
        ),
        migrations.AddField(
            model_name="engagementsettings",
            name="media_retention_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engagementsettings",
            name="message_retention_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
