# Generated by Django 5.2.17 on 2026-08-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(editable=False, max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("kind", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="organization.orgunit",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "external_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", models.F("parent_id")), _negated=True),
                        name="organization_orgunit_not_own_parent",
                    )
                ],
            },
        ),
    ]
