# Generated by Django 5.2.17 on 2026-08-22 21:57

import django.db.models.deletion
from django.db import migrations, models

import apps.identity.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("portal_id", models.CharField(editable=False, max_length=128, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("full_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("avatar_url", models.URLField(blank=True, max_length=2048)),
                ("module_roles", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_portal_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.orgunit",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "portal_id"],
            },
            managers=[
                ("objects", apps.identity.managers.UserManager()),
            ],
        ),
    ]
