# Generated by Django 5.2.17 on 2026-08-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position_group_external_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="position_group_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
