# Generated by Django 5.2.17 on 2026-08-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0007_unique_recovery_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
