# Generated by Django 5.2.17 on 2026-08-25 04:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_language_configurations"),
        ("identity", "0008_user_last_activity_at"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_name"], name="user_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["job_title"], name="user_job_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
