# Generated by Django 5.2.17 on 2026-08-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_user_user_name_trgm_idx_user_user_job_trgm_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessgrant",
            name="identity_access_grant_valid_pair",
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("module", "PLATFORM"), ("role", "ADMIN")),
                    models.Q(
                        ("module", "NEWS"),
                        ("role__in", ["MEMBER", "AUTHOR", "EDITOR", "MODERATOR", "ADMIN"]),
                    ),
                    models.Q(
                        ("module", "MESSENGER"), ("role__in", ["MEMBER", "MODERATOR", "ADMIN"])
                    ),
                    _connector="OR",
                ),
                name="identity_access_grant_valid_pair",
            ),
        ),
    ]
